WebBanHangOnline/Models/EF/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebBanHangOnline.Models.EF
{
    [Table("tb_ProductCategory")]
    public class ProductCategory : CommonAbstract
    {
        public ProductCategory()        
        {
        this.Products = new HashSet<Product>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        [Required]
        [StringLength(150)]
        public string Alias { get; set; }
        public string Description { get; set; }
        [StringLength(250)]
        public string Image { get; set; }
        [StringLength(250)]
        public string SeoTitle { get; set; }
        [StringLength(500)]
        public string SeoDescription { get; set; }
        [StringLength(250)]
        public string SeoKeywords { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

WebBanHangOnline/Areas/Admin/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Areas.Admin.Controllers
{
    public class ProductCategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/ProductCategory
        public ActionResult Index()
        {
            var item = db.ProductCategories;
            return View(item);
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                model.CreateDate = DateTime.Now;
                model.ModifiedrDate = DateTime.Now;
                model.Alias= WebBanHangOnline.Models.Commons.Filter.FilterChar(model.Title);
                db.ProductCategories.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            var item= db.ProductCategories.Find(id);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedrDate= DateTime.Now;
                model.Alias = WebBanHangOnline.Models.Commons.Filter.FilterChar(model.Title);
                db.ProductCategories.Attach(model);
                db.Entry(model).State=System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        { 
            var item=db.ProductCategories.Find(id);
            if (item != null)
            {
                db.ProductCategories.Remove(item);
                db.SaveChanges();
                return Json(new {success= true});
            }
            return Json(new {success= false});
        }

        [HttpPost]
        public ActionResult DeleteAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items.Length > 0 && items.Any())
                {
                    foreach (var item in items)
                    {
                        var ogj = db.ProductCategories.Find(Convert.ToInt32(item));
                        db.ProductCategories.Remove(ogj);
                        db.SaveChanges();
                    }
                }
                return Json(new { success= true});
            }
            return Json(new {success=false});
        }



    }
}

WebBanHangOnline/Areas/Admin/Views/ProductCategory/Add.cshtml
@model WebBanHangOnline.Models.EF.ProductCategory
@{
    ViewBag.Title = "Danh Muc Sản Phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/ProductCategory" class="nav-link">Tin tức</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/ProductCategory" class="nav-link">Danh Muc Sản Phẩm</a>
        </li>
    </ul>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Danh Muc Sản Phẩm Tin tức</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Sản Phẩm</a></li>
                    <li class="breadcrumb-item active">Danh Muc Sản Phẩm</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <br />

            <div class="bs-stepper-content">
                @using (Html.BeginForm("Add", "ProductCategory", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken();
                    @Html.ValidationSummary(true)
                    @*@Html.HiddenFor(x=>x.Id)*@
                    <!-- your steps content here -->
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tiêu đề</label>
                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tiêu đề" })
                            @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Alias</label>
                            @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Alias" })
                            @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Ảnh đại diện</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    @Html.TextBoxFor(x => x.Image, new { @class = "form-control", @id = "txtImage" })
                                </div>
                                <div class="input-group-append">
                                    <input type="button" value="Tải ảnh" onclick="BrowseServer('txtImage')" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Seo Title</label>
                            @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Seo Description</label>
                            @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Seo Keywords</label>
                            @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group">
                        <a href="/admin/ProductCategory" class="btn btn-danger">Quay lại</a>
                        <button type="submit" class="btn btn-primary">Thêm mới</button>
                    </div>

                }

            </div>
        </div>
        <div class="card-body">
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }

    </script>
}

WebBanHangOnline/Areas/Admin/Views/ProductCategory/Edit.cshtml
@model WebBanHangOnline.Models.EF.ProductCategory
@{
    ViewBag.Title = "Danh Muc Sản Phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/ProductCategory" class="nav-link">Tin tức</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/ProductCategory" class="nav-link">Danh Muc Sản Phẩm</a>
        </li>
    </ul>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Danh Muc Sản Phẩm Tin tức</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Sản Phẩm</a></li>
                    <li class="breadcrumb-item active">Danh Muc Sản Phẩm</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <br />

            <div class="bs-stepper-content">
                @using (Html.BeginForm("Edit", "ProductCategory", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken();
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x => x.Id);
                    @Html.HiddenFor(x => x.CreateDate);
                    @*@Html.HiddenFor(x=>x.Id)*@
                    <!-- your steps content here -->
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tiêu đề</label>
                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tiêu đề" })
                            @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Alias</label>
                            @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Alias" })
                            @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Ảnh đại diện</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    @Html.TextBoxFor(x => x.Image, new { @class = "form-control", @id = "txtImage" })
                                </div>
                                <div class="input-group-append">
                                    <input type="button" value="Tải ảnh" onclick="BrowseServer('txtImage')" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Seo Title</label>
                            @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Seo Description</label>
                            @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Seo Keywords</label>
                            @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control" })
                        </div>


                    </div>
                    <div class="form-group">
                        <a href="/admin/ProductCategory" class="btn btn-danger">Quay lại</a>
                        <button type="submit" class="btn btn-primary">Cập nhật</button>
                    </div>

                }

            </div>
        </div>
        <div class="card-body">
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }

    </script>
}

WebBanHangOnline/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<WebBanHangOnline.Models.EF.ProductCategory>

@*@using PagedList.Mvc;
    @using PagedList;*@

@{
    ViewBag.Title = "Danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/ProductCategory" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>
}


<!-- Content Wrapper. Contains page content -->
@*<div class="content-wrapper">*@
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lý @ViewBag.Title</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách @ViewBag.Title</h3>

            <div class="card-tools">
                <a href="/Admin/ProductCategory/add" class="btn btn-primary">Thêm mới</a>
                <a href="#" class="btn btn-danger" id="btnDeleteAll"> Xóa Hết</a>
            </div>
        </div>
        <div class="card-body">
            @*<div class="row">
                    <div class="col-6">
                        @using (Html.BeginForm("index", "ProductCategory", FormMethod.Get, new { }))
                        {
                            <div class="input-group input-group-sm">
                                @Html.TextBox("Searchtext", new { @class = "form-control" })
                                <span class="input-group-append">
                                    <button type="submit" class="btn btn-info btn-flat">Tìm Kiếm</button>
                                </span>
                            </div>
                        }
                    </div>
                </div>*@
            <table class="table table-hover">
                <thead>
                    <tr class="text-center">
                        <th><input type="checkbox" id="selectALL" /></th>
                        <th>STT</th>
                        <th>Tiêu đề</th>
                        <th>Ngày tạo</th>
                        <th>Ảnh đại diên</th>
                        <th>Hiển thị</th>
                        <th style="width:150px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = 1; /*((ViewBag.Page - 1) * ViewBag.PageSize) + 1;*/
                        foreach (var item in Model)
                        {
                            //var strCheck = item.IsActive ? "<i class='fa fa-check text-success'></i>" : "<i class='fas fa-times text-danger'></i>";

                            <tr id="trow_@item.Id" class="text-center">
                                <td><input type="checkbox" class="cbkItem" value="@item.Id" /></td>
                                <td>@i</td>
                                <td style="width:300px;text-align:center;">@item.Title</td>
                                <td>@item.CreateDate.ToString("dd//MM//yyyy")</td>
                                @*<td>
                                        <a href='#' data-id="@item.Id" class="btnActive">  @Html.Raw(strCheck)</a>
                                    </td>*@
                                <td><img src="@item.Image" style="width:50px"</td>
                                <td>
                                    <a href="/admin/ProductCategory/edit/@item.Id" class="btn btn-primary btn-sm">Sửa</a>
                                    <a href="#" data-id="@item.Id" class="btn btn-danger btn-sm btnDelete">Xóa</a>

                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="6">Không có bản ghi nào</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@*</div>*@
<!-- /.content-wrapper -->

@section scripts{
    <script>

        $(document).ready(function () {



            $('body').on('change', '#selectALL', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                    } else {
                        checkbox.attr('selected', '');
                    }
                })
            })



            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id")
                var conf = confirm("Ban co muon xoa ban ghi nay khong");
                if (conf === true) {
                    $.ajax({
                        url: '/admin/ProductCategory/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    })

                }

            })
        })
        $(document).ready(function () {
            // Đoạn mã cho sự kiện click trên .btnActive
            $('body').on('click', '.btnActive', function (e) {
                e.preventDefault(); // Đảm bảo gọi đúng e.preventDefault()
                var btn = $(this);
                var id = btn.data("id");

                $.ajax({
                    url: '/admin/ProductCategory/IsActive',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            if (rs.isActive) {
                                btn.html("<i class='fa fa-check text-success'></i>");
                            } else {
                                btn.html("<i class='fas fa-times text-danger'></i>");
                            }
                        }
                    }
                });
            });

            // Đoạn mã cho sự kiện click trên #btnDeleteAll
            $('body').on('click', '#btnDeleteAll', function (e) {
                e.preventDefault(); // Đảm bảo gọi đúng e.preventDefault()
                var str = "";
                debugger;
                var checkbox = $(this).parents('.card').find('tbody tr td input:checkbox');
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        $(this).attr('selected', 'checked'); // Sử dụng $(this) thay vì checkbox
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        $(this).attr('selected', ''); // Sử dụng $(this) thay vì checkbox
                    }
                });

                if (str.length > 0) {
                    var cof = confirm("ban co muon xoa het khong");
                    if (cof === true) {
                        $.ajax({
                            url: '/admin/ProductCategory/DeleteAll',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            });
        });


    </script>
}